### ISSUE TITLE
Oops, mkvmerge problème

### ISSUE THREAD

**Issue by M0dM** [EudesRobin/mux-mkv_srt#1]
Yop,

J'étais en train de bosser pour te faire un container docker tranquillou pour mettre le répersoire de série en entrée dans un volume et qu'il te ressource ça tout propre dans le même volume mais j'ai eu un petit soucis.
Ton script ne semble pas aimer le combo debian + python 3.5

J'ai pas trop pris le temps de plus investiguer que ça mais ça a l'air de planter au niveau de l'appel à mkvmerge.

Voilou.
Si t'arrive à réparer ça, je te finirai le container docker.
Bonne soirée.

Benoit

```
root@13064963b010:~# python mux.py -d My.tv_serie.S01.1080p.WEB-DL-Team/
['My.tv_serie.', 'S01.', '1080p.WEB-DL-Team']
3
My.tv_serie.S01.VOSTFR.1080p.WEB-DL-Team created
working on My.tv_serie.S01.VOSTFR.1080p.WEB-DL-Team/My.tv_serie.S01E01.VOSTFR.1080p.WEB-DL-Team.mkv
Traceback (most recent call last):
  File "mux.py", line 113, in <module>
    mux(os.path.normpath(arg),mkvmerge)
  File "mux.py", line 57, in mux
    result = subprocess.check_output(mkvmerge+' --output'+' "'+outputfile+'" '+opt_original+' "'+itemvid+'" '+opt_sub+' "'+itemsub+'" ', shell=True, stderr=subprocess.STDOUT)
  File "/usr/local/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'mkvmerge --output "My.tv_serie.S01.VOSTFR.1080p.WEB-DL-Team/My.tv_serie.S01E01.VOSTFR.1080p.WEB-DL-Team.mkv" --no-global-tags "My.tv_serie.S01.1080p.WEB-DL-Team/My.tv_serie.S01E01.1080p.WEB-DL-Team.mkv" --language 0:fre --default-track 0:yes "My.tv_serie.S01.1080p.WEB-DL-Team/My.tv_serie.S01E01.1080p.WEB-DL-Team.srt" ' returned non-zero exit status 1
root@13064963b010:~# 
```

**Comment by EudesRobin** [comment]
je viens de tester sous une VM Debian 8.3 que j'avais, avec python 3.5.1 ; mkvmerge installé tout bien, j'arrive pas à reproduire l'erreur (en lançant la même commande)

hum... Si tu remplaces subprocess.chekoutput(...) par un os.system(...), on y verra p'tre plus clair (?). La seule "différence" c'est docker...

Si tu lance la commande

> mkvmerge --output "My.tv_serie.S01.VOSTFR.1080p.WEB-DL-Team/My.tv_serie.S01E01.VOSTFR.1080p.WEB-DL-Team.mkv" --no-global-tags "My.tv_serie.S01.1080p.WEB-DL-Team/My.tv_serie.S01E01.1080p.WEB-DL-Team.mkv" --language 0:fre --default-track 0:yes "My.tv_serie.S01.1080p.WEB-DL-Team/My.tv_serie.S01E01.1080p.WEB-DL-Team.srt"

dans ton docker, ça donne quoi ? Celle ci est à priori valide (aucun soucis avec le binaire mkvmerge dispo après install selon les inscrictions -> https://mkvtoolnix.download/downloads.html )

Est-ce que tu as bien config ton répertoire pour que ton container docker ai les bon droits d'accès ?

**Comment by M0dM** [comment]
Je devais être fatigué, ça marche très bien.
Je te fais une PR pour le container Docker.

Si tu veux le mettre sur ton propre répo docker, change juste benoitbrayer/mux-mkv_srt 
par EudesRobin/mux-mkv_srt par exemple ;)

**Comment by EudesRobin** [comment]
Merci, j'intègre tout ça ;)
