### ISSUE TITLE
Is it working in Linux?

### ISSUE THREAD

**Issue by xcom169** [EudesRobin/mux-mkv_srt#10]
Hello!

I tried it in Linux but it won't find any video, subtitle files.

**Comment by M0dM** [comment]
Yes :D.

For example docker image was build on top of debian jessie.

**Comment by EudesRobin** [comment]
it can work on linux, you just need Python and mkvmerge.

```
C:\TV
├───My.tv_serie.S01.1080p.WEB-DL-Team
│   ├───My.tv_serie.S01E01.1080p.WEB-DL-Team.mkv
│   └───My.tv_serie.S01E01.1080p.WEB-DL-Team.srt
```


In this eg, your episode ( My.tv_serie.S01E01.1080p.WEB-DL-Team.mkv ) is in My.tv_serie.S01.1080p.WEB-DL-Team

Your str file has to be named like your mkv file and in same directory, or it won't match.

What was the output when you tried (any errors, warning ... ) ?

**Comment by M0dM** [comment]
I think this issue can be closed. Don't hesitate to re-open and ping @EudesRobin if you have any other question ;).
