### ISSUE TITLE
"Regex failed to split..."

### ISSUE THREAD

**Issue by Barbait** [EudesRobin/mux-mkv_srt#11]
Hi, i'm tring to mux a series, i follow the instructions (i have both of the requirements: ad mkvmerge to PATH and installed python, also added that to PATH), the problem is that it cannot even start muxing because of the error: "Regex fail to split video filename in 3 parts : title_serie - saison/episode - tech/team"

Here's a screenshot:
https://ibb.co/HpwW9cD

**Comment by EudesRobin** [comment]
Hello,

Something in the filename is not handled right i think , I'm gonna check that asap.

Best regards,

**Comment by EudesRobin** [comment]
Hello,

Your files don't have the right filename format, thats why it fails.
But your folder name is OK.

You need to rename you files like this : 

first : tv show name , here American Vandal
second :  saison/ ep , here S1E01 
third : team / codec / episode name ... whatever.

it's very important to follow that order so the software can split filename in 3 part using this pattern 
`'([S][0-9]{1,2}[E][0-9]{1,2}.)+'`

It searchs for ' S number E number '  , and it must be between tv show name  and codec-team so the filename is split in 3 when it extract this subpart.

You must follow this pattern to rename your files like this : 
for eg : "American Vandal S1E01  - Fatti concerti - lll.mp4"

Best regards,
Robin

**Comment by Barbait** [comment]
I keep having the error, i've renamed the episodes in two ways:
American_Vandal S01E01 - title - 123.mp4
American Vandal S01E01 - title - 123.mp4

**Comment by EudesRobin** [comment]
Did you rename all your files this way ?

I check with online python interpreter ( https://www.onlinegdb.com/online_python_interpreter )  this code  : 

```
import os, sys
import glob, re, subprocess

resultwithdot = re.sub('\s', '.', "American Vandal S01E01 - title - 123.mp4") 
resultsplit = re.split('([S][0-9]{1,2}[E][0-9]{1,2}.)+',resultwithdot,flags=re.IGNORECASE)

print(len(resultsplit))
```

len = 3 , so it's okay and we don't execute this code  : 

```
                if len(resultsplit)!=3:
                    uprint('Regex fail to split video filename in 3 parts : title_serie - saison/episode - tech/team ')
                    sys.exit(1)

```

**Comment by Barbait** [comment]
yes, i've used Filebot to rename both videofiles and subtitle files that way.
The problem is not the lines that you indicated, but before that (line 30-35):
`# output dir name
            outputdirwithdot = re.sub(' ', '.', os.path.basename(dir))  
            resultsplit = re.split('([S][0-9]{1,2}.)+',outputdirwithdot,flags=re.IGNORECASE)
            if len(resultsplit)!=3:
                uprint('Regex fail to split folder name in 3 parts : title_serie - saison - tech/team ')
                return sys.exit(1)`

Because my output error is:
`Regex fail to split folder name in 3 parts : title_serie - saison - tech/team`
and not:
`Regex fail to split video filename in 3 parts : title_serie - saison/episode - tech/team`

the difference is that in the first the error says only "saison" and in the second says "saison/episode"

EDIT: i didn't notice but i'm getting the second type of error, should i try with other name variants?

EDIT 2: I'm trying with another series. The results are theese: https://ibb.co/Nykmh4d

**Comment by EudesRobin** [comment]
Oh,

When you have this error : 

> Regex fail to split folder name in 3 parts : title_serie - saison - tech/team

It means that your folder name is not following this format : 

`name S ' number ' codec/team 
`
It more or less the same thing with video filename, but here, we are just looking to split folder name in 3 part using season number . Your folder must have a name like

`Amazing TV Show S01 WEB-DL - SuperTeam`

Check 2 things : 
- folder name  , we must find S'season number' in folder name ( not at begin or end of name )
- video filename , we must find S'season number'E'episode number' in file name ( not at begin or end of name )

I will try to improve my doc with more eg about folder / filename format soon :) 

It should be okay now :) 

Best regards,

**Comment by Barbait** [comment]
Yes, now it works. The only problem i encouter is that the subtitle track is recognized as "french" and not "italian"

EDIT: found & changed the piece of code.

**Comment by EudesRobin** [comment]
Yeah, I don't remember why I hardcoded some stuff in french, i create a new issue about this https://github.com/EudesRobin/Mux-Sub/issues/12
