### ISSUE TITLE
Docker auto-build

### ISSUE THREAD

**Issue by M0dM** [EudesRobin/mux-mkv_srt#5]
I can't setup docker hub auto-build by myself because I am not project creator.
I thought I could being projet member but I can't.

To do so, you need to follow this procedure : 
https://docs.docker.com/docker-hub/builds/

**Comment by EudesRobin** [comment]
I setup that, it should work (I'm also a begginer with docker ;) ).

For now, it just build on master, with latest tag.

**Comment by M0dM** [comment]
If you use gitflow it's not a problem because we will push only release and hotfix to the master branch.
develop branch witll be or working branch.
So, building docker containers from the master branch is a good practice because only "stable" builds will belong to the master branch.
